### ISSUE TITLE
 RevPiPyLoad prevents loading PIN Dropdown at RevPi Nodes

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/node-red-contrib-revpi-nodes#10] opened 2020-12-18 14:34 UTC
https://revolution.kunbus.de/forum/viewtopic.php?f=48&t=2482

It seems RevPiPyLoad is interfering with the RevPi Nodes. Needs to be investigated.

**Comment by naruxde** [comment] 2021-02-04 08:57
Is there any information yet?

Where could there be an overlap in the systems? Why should the service affect NodeRed nodes?

RevPiPyLoad could open ports 55123 and 55234 and use them for the XML-RPC and the process image server.

**Comment by jgerlach-erminas** [comment] 2021-02-04 09:34
Hi,
I'm still trying to reproduce this bug. My only guess is that it might be a similar situation to https://github.com/erminas/node-red-contrib-revpi-nodes/issues/9 where concurrent access to the process image caused problems. I will get back to you when I have made further analysis. I don't think it's network related, ports 55123 and 55234 aren't used in the RevPi Nodes context as far I know.

**Comment by jgerlach-erminas** [comment] 2021-02-19 13:34
I wasn't able to reproduce this bug, I have requested further information in the forum thread

**Comment by dfilsinger-erminas** [comment] 2022-05-30 13:40
It has been fixed in the new versions.
We could not reproduce it with version 1.0.9 and server 1.0.4.

**Closed as completed by dfilsinger-erminas** 2022-05-30 13:40 UTC
Labels: bug
