### ISSUE TITLE
multiple input node missing from the palette

### ISSUE THREAD

**Issue by ch4mploo** [erminas/node-red-contrib-revpi-nodes#7] opened 2020-07-07 03:55 UTC
Hi, recently after updating the node to version 1.0.6, the multiple input node can no longer be found in the palette. I find this odd so I start to explore the source codes just to see if I can find something is wrong.

Upon inspecting **_revpi-nodes.html_**, I found a inconsistency. At the RED.nodes.registerType() for multiple input part (line 243 to 304), the object keys are encased in single quotes (looks like JSON format). However, upon inspecting other RED.nodes.registerType(), for example, the single input part (line 190 to 224), I can see that the object keys are written in a normal Javascript way (without single quotes).

Not sure if this is done intentionally or not. Hope I can get enlightened upon this issue.

**Comment by dfilsinger-erminas** [comment] 2022-05-30 13:36
It has been fixed in the new versions.
We could not reproduce it with version 1.0.9 and server 1.0.4.

**Closed as completed by dfilsinger-erminas** 2022-05-30 13:36 UTC
